name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (excluding test folder)
        run: |
          if [ -d "backend" ]; then cd backend && npm install && cd ..; fi
          if [ -d "frontend" ]; then cd frontend && npm install && cd ..; fi

      - name: Run tests (excluding test folder)
        run: |
          if [ -d "backend" ]; then cd backend && npm test && cd ..; fi
          if [ -d "frontend" ]; then cd frontend && npm test && cd ..; fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: |
          echo "Deploying project..."
